- hosts: dbserver
  become: yes
  vars_files:
    - vars/default.yml

  tasks:

       - name: Saving random test file to /home/adi91/backup
         fetch:
                 src: /var/log/syslog
                 dest: /home/adi91/backup/databaselogs/
                 flat: yes
         
